name: Node CI
on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org

      - name: Log Environment
        run: |
          echo "Node version $(node --version)"
          echo "NPM version $(npm --version)"
          echo "System Info $(uname -a)"

      - name: Install Dependencies
        run: npm i

      - name: Format
        run: npm run format

      - name: Lint
        run: npm run lint

  deploy:
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance

    runs-on: ubuntu-22.04
    needs: test

    # Run only on pushing to main
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org

      - name: Log Environment
        run: |
          echo "Node version $(node --version)"
          echo "NPM version $(npm --version)"
          echo "System Info $(uname -a)"

      - name: Install Dependencies
        run: npm i

      - name: Release to NPM
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
